In [2]:
import numpy as np
from javelin.structure import Structure
from javelin.energies import LennardJonesEnergy
from javelin.modifier import SetDisplacementNormalXYZ
from javelin.fourier import Fourier
from javelin.mc import MC
from ase.io import write
import multiprocessing


def create_structure(n=15):
    x = np.random.normal(0, 0.01, size=n**3)
    y = np.random.normal(0, 0.01, size=n**3)
    z = np.random.normal(0, 0.01, size=n**3)
    structure = Structure(symbols=np.random.choice(
        ['Au', 'Cu'], n**3), positions=np.vstack((x, y, z)).T, unitcell=5)
    structure.reindex([n, n, n, 1])
    return structure


e1 = LennardJonesEnergy(1, 1.05, atom_type1=79, atom_type2=79)
e2 = LennardJonesEnergy(1, 1.0,  atom_type1=79, atom_type2=29)
e3 = LennardJonesEnergy(1, 0.95, atom_type1=29, atom_type2=29)


def relax(structure):
    mc = MC()
    mc.add_modifier(SetDisplacementNormalXYZ(0, 0, 0.02, 0, 0.02, 0, 0.02))
    mc.temperature = 0.001
    mc.cycles = 1000
    nl = structure.get_neighbors(0)
    mc.add_target(nl, e1)
    mc.add_target(nl, e2)
    mc.add_target(nl, e3)
    return mc.run(structure)

In [3]:
structure = create_structure(5)
structure.atoms

             Z symbol         x         y         z
i j k site
0 0 0 0     29     Cu  0.000110  0.004096 -0.006466
    1 0     29     Cu -0.015719 -0.006858 -0.005405
    2 0     29     Cu  0.004149  0.004535  0.001423
    3 0     79     Au -0.005977  0.018506 -0.006081
    4 0     79     Au -0.022440  0.006047  0.010128
...         ..    ...       ...       ...       ...
4 4 0 0     29     Cu  0.026996 -0.005462  0.013791
    1 0     79     Au -0.019786 -0.001143  0.014204
    2 0     29     Cu  0.005361  0.017954  0.000870
    3 0     29     Cu -0.009598  0.011946  0.000995
    4 0     79     Au -0.004950 -0.010008 -0.006938

[125 rows x 5 columns]

             Z symbol         x         y         z
i j k site
0 0 0 0     79     Au  0.007024  0.002412 -0.008818
    1 0     29     Cu  0.012860  0.006218 -0.005634
    2 0     79     Au  0.009234 -0.003228 -0.008058
    3 0     29     Cu  0.005962 -0.013754 -0.009233
    4 0     79     Au -0.006655  0.001593 -0.004819
...         ..    ...       ...       ...       ...
4 4 0 0     79     Au -0.006269  0.010676 -0.004135
    1 0     29     Cu  0.000077 -0.006015 -0.006919
    2 0     79     Au -0.017690  0.005769  0.008337
    3 0     79     Au -0.005102  0.000591  0.002708
    4 0     29     Cu  0.006412  0.007402 -0.012923

[125 rows x 5 columns]

In [5]:
from custom.analysis import get_average_site_positions
get_average_site_positions(structure, 5)

[(-0.00126, 0.00171, 0.00075)]

In [6]:
from custom.io import bash

In [7]:
bash("scatty")

 Please start the program by writing ./scatty [input file name stem]